"""Add customer table and foreign key to proofs

Revision ID: a7942eaaaca5
Revises: 20241028_0002
Create Date: 2025-10-29 09:52:48.754187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7942eaaaca5'
down_revision = '20241028_0002'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_index(op.f('ix_decisions_proof_version_id'), table_name='decisions')
    op.alter_column('designers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_designers_email'), table_name='designers')
    op.add_column('proofs', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.alter_column('proofs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proofs', 'designer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_proofs_designer_id'), table_name='proofs')
    op.create_foreign_key(None, 'proofs', 'customers', ['customer_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'smtp_use_tls',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'smtp_use_ssl',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'smtp_use_ssl',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('users', 'smtp_use_tls',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'designer'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'proofs', type_='foreignkey')
    op.create_index(op.f('ix_proofs_designer_id'), 'proofs', ['designer_id'], unique=False)
    op.alter_column('proofs', 'designer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('proofs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_column('proofs', 'customer_id')
    op.create_index(op.f('ix_designers_email'), 'designers', ['email'], unique=True)
    op.alter_column('designers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index(op.f('ix_decisions_proof_version_id'), 'decisions', ['proof_version_id'], unique=False)
    op.drop_table('customers')
    # ### end Alembic commands ###
